[package]
name = "keshav/aba"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]


[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"